### PR TITLE
Explicitly create extension dir

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-5-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-5-2`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-5-3`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-5-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-5-5`

**Review by waseem-h — APPROVED** [review]

**Pull request merged**
