### PR TITLE
Updating docker image tag

### PR DESCRIPTION
**Pull request by Muneebstakater**

### CODE REVIEW

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-docker/sonarqube/commit/6532fc88f24903284f5783184f194ed2e79e7711/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-docker/sonarqube/commit/a898c97fad2f820c934c761486e74d0a74859968/checks) has Failed!

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull stakater/sonarqube:SNAPSHOT-PR-8.9.7-community-18-a348f624`

**Comment by stakater-user** [comment]
@Muneebstakater Image is available for testing. `docker pull stakater/sonarqube:SNAPSHOT-PR-8.9.7-community-18-6a135c6f`

**Review by TehreemNisa — APPROVED** [review]

**Pull request merged**
