### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by hazim1093**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.tools.stackator.com/job/stakater-docker%20organization/job/sonarqube/job/PR-1/1/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.tools.stackator.com/job/stakater-docker%20organization/job/sonarqube/job/PR-1/2/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-4`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-5`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-6`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-7`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-8`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-9`

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 10](https://jenkins.tools.stackator.com/job/stakater-docker%20organization/job/sonarqube/job/PR-1/10/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 11](https://jenkins.tools.stackator.com/job/stakater-docker%20organization/job/sonarqube/job/PR-1/11/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:SNAPSHOT-PR-1-12`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-14`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-15`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-17`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-1`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-18`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-19`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-20`

**Comment by stakater-user** [comment]
@hazim1093 Yikes! You better fix it before anyone else finds out! [Build 21](https://jenkins.tools.stackator.com/job/stakater-docker%20organization/job/sonarqube/job/PR-1/21/) has Failed!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-22`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-23`

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-24`

**Review by rasheedamir — APPROVED** [review]
Well done!

**Comment by stakater-user** [comment]
@hazim1093 Image is available for testing. `docker pull docker.io/stakater/sonarqube:7.1-jdk1.8-centos7-SNAPSHOT-PR-1-2`

**Pull request merged**
